// ⚠️ Do not edit this file! It is created by the pages_js_create.sh script.
const pages = {
    "home": `
<h1>all AI<br>no blabla<br><a href="mailto:bla@nohype.ai">bla@nohype.ai</a></h1>

<h2>
    What?<br>
    <a href="#services">
        AI, Data, Architecture, Apple
    </a>
</h2>
<h2>
    How?<br>
    <a href="#services">
        Consulting, Training, Engineering
    </a>
</h2>
    `,
    "imprint": `
<h1>Imprint</h1>
<table>
    <tbody>
        <tr>
            <td>Business Name</td>
            <td>Nohype AI GmbH</td>
        </tr>
        <tr>
            <td>UID</td>
            <td>CHE-185.499.430</td>
        </tr>
        <tr>
            <td>CH-ID</td>
            <td>CH-170-4023713-9</td>
        </tr>
        <tr>
            <td>Address</td>
            <td>Nohype AI GmbH<br>c/o Domiix.ch GmbH<br>Baarerstrasse 107<br>6300 Zug, Switzerland</td>
        </tr>
        <tr>
            <td style="padding-right: 20px;">
                Owner & Managing Director
            </td>
            <td>Sebastian Fichtner</td>
        </tr>
        <tr>
            <td>Content Editor</td>
            <td>Sebastian Fichtner</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>hi@nohype.ai</td>
        </tr>
    </tbody>
</table>
    `,
    "people": `
<div style="display: flex; gap: 80px; align-items: start; flex-wrap: wrap;">
    <div style="max-width: 200px; text-align: center;">
        <a href="team/sebastian-cv.pdf" target="_blank"><img src="team/sebastian.jpg" alt="Sebastian Fichtner" style="max-width: 200px; border-radius: 50%; object-fit: cover; display: block; margin: 0 auto; transition: transform 0.2s ease;" onmouseover="this.style.transform='scale(1.05)'" onmouseout="this.style.transform='scale(1)'"></a>
        <p>
            Sebastian Fichtner<br>
            AI, Architecture, Apple<br>
            <a href="mailto:sebastian@nohype.ai">sebastian@nohype.ai</a><br><br>
            <span style="display: flex; gap: 20px; justify-content: center;">
                <a href="https://www.linkedin.com/in/codeface-io" target="_blank"><img src="icons/linkedin.svg" alt="LinkedIn" style="width: 24px; height: 24px; vertical-align: middle; filter: invert(1) brightness(0.5);"></a>
                <a href="team/sebastian-cv.pdf" target="_blank"><img src="icons/file-earmark-pdf.svg" alt="CV" style="width: 24px; height: 24px; vertical-align: middle; filter: invert(1) brightness(0.5);"></a>
                <a href="https://github.com/nohype-ai" target="_blank"><img src="icons/github.svg" alt="GitHub" style="width: 24px; height: 24px; vertical-align: middle; filter: invert(1) brightness(0.5);"></a>
            </span>
        </p>
    </div>
    <div style="max-width: 200px; text-align: center;">
        <a href="https://www.linkedin.com/in/manuelahebel" target="_blank"><img src="team/manuela.jpg" alt="Manuela Hebel" style="max-width: 200px; border-radius: 50%; object-fit: cover; display: block; margin: 0 auto; transition: transform 0.2s ease;" onmouseover="this.style.transform='scale(1.05)'" onmouseout="this.style.transform='scale(1)'"></a>
        <p>
            Manuela Hebel<br>
            Data Strategy, Product<br>
            <a href="mailto:manuela@nohype.ai">manuela@nohype.ai</a><br><br>
            <span style="display: flex; gap: 20px; justify-content: center;">
                <a href="https://www.linkedin.com/in/manuelahebel" target="_blank"><img src="icons/linkedin.svg" alt="LinkedIn" style="width: 24px; height: 24px; vertical-align: middle; filter: invert(1) brightness(0.5);"></a>
                <a href="https://manuela-hebel.com/ueber-mich" target="_blank"><img src="icons/globe2.svg" alt="Website" style="width: 24px; height: 24px; vertical-align: middle; filter: invert(1) brightness(0.5);"></a>
            </span>
        </p>
    </div>
    <!--<div style="max-width: 250px; text-align: center;">
        <a href="https://www.linkedin.com/in/tintenklecks" target="_blank"><img src="team/ingo.jpg" alt="Ingo Böhme" style="max-width: 250px; border-radius: 50%; object-fit: cover; display: block; margin: 0 auto; transition: transform 0.2s ease;" onmouseover="this.style.transform='scale(1.05)'" onmouseout="this.style.transform='scale(1)'"></a>
        <p>
            Ingo Böhme<br>
            Consultant, AI Architect<br>
            <a href="mailto:ingo@nohype.ai">ingo@nohype.ai</a><br><br>
            <span style="display: flex; gap: 20px; justify-content: center;">
                <a href="https://www.linkedin.com/in/tintenklecks" target="_blank"><img src="icons/linkedin.svg" alt="LinkedIn" style="width: 24px; height: 24px; vertical-align: middle; filter: invert(1) brightness(0.5);"></a>
                <a href="https://x.com/IBMobile" target="_blank"><img src="icons/twitter-x.svg" alt="X" style="width: 24px; height: 24px; vertical-align: middle; filter: invert(1) brightness(0.5);"></a>
            </span>
        </p>
    </div>-->
</div>
    `,
    "services": `
<h1>@<br>your<br>service</h1>

<section class="grid">
    <div class="grid-cell">
        <h2>Agentic Engineering</h2>
        <p>
            We don't "vibe code" products. Our AI-driven development process is built from engineering discipline. The result is an incredible pace that sustains long-term and produces quality maintainable software.
        </p>
    </div>

    <div class="grid-cell">
        <h2>AI Engineering</h2>
        <p>
            We don't just use AI to build software, we also build software that uses AI: intelligent features and interfaces that unlock new types of products, services and business models.
        </p>
    </div>

    <div class="grid-cell">
        <h2>Data Engineering</h2>
        <p>
            At the heart of AI is data. Most uses cases in business intelligence and automation surprisingly don't need "AI" in the modern sense but actually require classic methods of data science.
        </p>
    </div>

    <div class="grid-cell">
        <h2>Software Architecture</h2>
        <p>
            The key to agentic productivity is agentic quality assurance. For agents to accomplish big things without help, they need an environment that guides them towards real business objectives.
            <!--Architecture is the art of abstraction and overview - of putting all the puzzle pieces together, across languages, domains, people and cultures. In the age of AI we need systems that guide agents to produce consistent, predicatable, inspectable, and maintainable software.-->
        </p>
    </div>

    <div class="grid-cell">
        <h2>Apple Engineering</h2>
        <p>
            Apple platforms are excellent at local AI. And we are excellent at developing for Apple platforms. We build state of the art iOS and macOS applications, including remote- and local AI features.
        </p>
    </div>

    <!--<div class="grid-cell">
        <h2>Say Hi!</h2>
        <h2>
            <a href="mailto:hi@nohype.ai">
                hi@nohype.ai
            </a>
        </h2>
    </div>-->
</section>

<!--<h2>
    Say Hi<br>
    <a href="mailto:hi@nohype.ai">
        hi@nohype.ai
    </a>
</h2>-->
    `,
    "software": `
<h1>we<br>make<br>things</h1>

<section class="grid">
    <div class="grid-cell">
        <h2><a href="https://codeface.io" target="_blank" rel="noopener noreferrer">codeface.io</a></h2>
        <p>
            Codeface visualizes the architecture (structure), quality and metrics of software via built-in language-intelligence. On the Mac App Store.
        </p>
    </div>

    <div class="grid-cell">
        <h2><a href="https://flowlistapp.com" target="_blank" rel="noopener noreferrer">flowlistapp.com</a></h2>
        <p>
            Flowlist is an animated hierarchical task list that unifies note taking, creative writing & project management. On the Mac App Store.
        </p>
    </div>

    <div class="grid-cell">
        <h2><a href="https://MacStack.dev" target="_blank" rel="noopener noreferrer">macstack.dev</a></h2>
        <p>
            MacStack allows declaring all aspects of a Mac tech stack as config and applies it in place non-destructively. Available as Homebrew formula.
        </p>
    </div>

    <div class="grid-cell">
        <h2><a href="https://omastack.dev" target="_blank" rel="noopener noreferrer">omastack.dev</a></h2>
        <p>
            OmaStack allows declaring an Omarchy tech stack as config and applies it in place, installing, updating, configuring and removing software accordingly.
        </p>
    </div>

    <div class="grid-cell">
        <h2><a href="https://olivemail.ai" target="_blank" rel="noopener noreferrer">olivemail.ai</a></h2>
        <p>
            Olive Mail turns existing email accounts into context for agents. A local CLI lets agents read, draft, and send (if permitted), without touching credentials.
        </p>
    </div>
</section>
    `,
};
