// ⚠️ Do not edit this file! It is created by the pages_js_create.sh script.
const pages = {
    "home": `
<h1>all AI<br>no Blabla<br><a href="mailto:bla@nohype.ai">bla@nohype.ai</a></h1>

<p>We engineer AI systems, consult on what is worth building and what should be integrated instead, and train the people who will run them.

<p>We start from an outcome you can measure, and we can fix the price before any UX or architecture work. You own all created code.</p>
    `,
    "imprint": `
<h1 style="margin-top: -7px;">Imprint</h1>
<table>
    <tbody>
        <tr>
            <td>Business Name</td>
            <td>Nohype AI GmbH</td>
        </tr>
        <tr>
            <td>UID</td>
            <td>CHE-185.499.430</td>
        </tr>
        <tr>
            <td>CH-ID</td>
            <td>CH-170-4023713-9</td>
        </tr>
        <tr>
            <td>Address</td>
            <td>Nohype AI GmbH<br>c/o Domiix.ch GmbH<br>Baarerstrasse 107<br>6300 Zug, Switzerland</td>
        </tr>
        <tr>
            <td style="padding-right: 20px;">
                Owner & Managing Director
            </td>
            <td>Sebastian Fichtner</td>
        </tr>
        <tr>
            <td>Content Editor</td>
            <td>Sebastian Fichtner</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>hi@nohype.ai</td>
        </tr>
    </tbody>
</table>
    `,
    "people": `
<div style="display: flex; gap: 80px; align-items: start; flex-wrap: wrap;">
    <div style="max-width: 200px; text-align: center;">
        <a href="team/sebastian-cv.pdf" target="_blank"><img src="team/sebastian.jpg" alt="Sebastian Fichtner" style="max-width: 200px; border-radius: 50%; object-fit: cover; display: block; margin: 0 auto; transition: transform 0.2s ease;" onmouseover="this.style.transform='scale(1.05)'" onmouseout="this.style.transform='scale(1)'"></a>
        <p>
            Sebastian Fichtner<br>
            Founder, AI Architect<br>
            <a href="mailto:sebastian@nohype.ai">sebastian@nohype.ai</a><br><br>
            <span style="display: flex; gap: 20px; justify-content: center;">
                <a href="https://www.linkedin.com/in/codeface-io" target="_blank"><img src="icons/linkedin.svg" alt="LinkedIn" style="width: 24px; height: 24px; vertical-align: middle; filter: invert(1) brightness(0.5);"></a>
                <a href="team/sebastian-cv.pdf" target="_blank"><img src="icons/file-earmark-pdf.svg" alt="CV" style="width: 24px; height: 24px; vertical-align: middle; filter: invert(1) brightness(0.5);"></a>
                <a href="https://github.com/nohype-ai" target="_blank"><img src="icons/github.svg" alt="GitHub" style="width: 24px; height: 24px; vertical-align: middle; filter: invert(1) brightness(0.5);"></a>
            </span>
        </p>
    </div>
    <div style="max-width: 200px; text-align: center;">
        <a href="https://www.linkedin.com/in/manuelahebel" target="_blank"><img src="team/manuela.jpg" alt="Manuela Hebel" style="max-width: 200px; border-radius: 50%; object-fit: cover; display: block; margin: 0 auto; transition: transform 0.2s ease;" onmouseover="this.style.transform='scale(1.05)'" onmouseout="this.style.transform='scale(1)'"></a>
        <p>
            Manuela Hebel<br>
            AI Consultant<br>
            <a href="mailto:manuela@nohype.ai">manuela@nohype.ai</a><br><br>
            <span style="display: flex; gap: 20px; justify-content: center;">
                <a href="https://www.linkedin.com/in/manuelahebel" target="_blank"><img src="icons/linkedin.svg" alt="LinkedIn" style="width: 24px; height: 24px; vertical-align: middle; filter: invert(1) brightness(0.5);"></a>
                <a href="https://manuela-hebel.com/ueber-mich" target="_blank"><img src="icons/globe2.svg" alt="Website" style="width: 24px; height: 24px; vertical-align: middle; filter: invert(1) brightness(0.5);"></a>
            </span>
        </p>
    </div>
    <!--<div style="max-width: 250px; text-align: center;">
        <a href="https://www.linkedin.com/in/tintenklecks" target="_blank"><img src="team/ingo.jpg" alt="Ingo Böhme" style="max-width: 250px; border-radius: 50%; object-fit: cover; display: block; margin: 0 auto; transition: transform 0.2s ease;" onmouseover="this.style.transform='scale(1.05)'" onmouseout="this.style.transform='scale(1)'"></a>
        <p>
            Ingo Böhme<br>
            Consultant, AI Architect<br>
            <a href="mailto:ingo@nohype.ai">ingo@nohype.ai</a><br><br>
            <span style="display: flex; gap: 20px; justify-content: center;">
                <a href="https://www.linkedin.com/in/tintenklecks" target="_blank"><img src="icons/linkedin.svg" alt="LinkedIn" style="width: 24px; height: 24px; vertical-align: middle; filter: invert(1) brightness(0.5);"></a>
                <a href="https://x.com/IBMobile" target="_blank"><img src="icons/twitter-x.svg" alt="X" style="width: 24px; height: 24px; vertical-align: middle; filter: invert(1) brightness(0.5);"></a>
            </span>
        </p>
    </div>-->
</div>
    `,
    "software": `
<h1>We<br>Make<br>Things</h1>

<h2><a href="https://codeface.io" target="_blank" rel="noopener noreferrer">Codeface</a></h2>
<h2><a href="https://MacStack.dev" target="_blank" rel="noopener noreferrer">MacStack</a></h2>
<h2><a href="https://omastack.dev" target="_blank" rel="noopener noreferrer">OmaStack</a></h2>
<h2><a href="https://flowlistapp.com" target="_blank" rel="noopener noreferrer">Flowlist</a></h2>
<h2><a href="https://olivemail.ai" target="_blank" rel="noopener noreferrer">Olive Mail</a></h2>
    `,
};
