#!/bin/zsh

set -e
setopt nullglob

{
  print -r -- "// ⚠️ Do not edit this file! It is created by the pages_js_create.sh script."
  print -r -- "const pages = {"

  for file in pages/*.html; do
    page_name=${file:t:r}  # basename without extension
    content=$(<"$file")    # read file into variable

    # Escape content for JS template literals:
    # - backslashes (keep them literal)
    # - backticks (don't terminate template literal)
    # - ${ (avoid accidental interpolation)
    escaped_content=$(printf "%s" "$content" | sed -e 's/\\/\\\\/g' -e 's/`/\\`/g' -e 's/\${/\\${/g')

    print -r -- "    \"${page_name}\": \`"
    print -r -- "${escaped_content}"
    print -r -- "    \`,"
  done

  print -r -- "};"
} > pages.js