#!/bin/zsh

echo "// ⚠️ Do not edit this file! It is created by the pages_js_create.sh script." > pages.js

echo "const pages = {" >> pages.js

for file in pages/*.html; do
    page_name=$(basename "$file" .html)
    echo "$page_name:" >> pages.js
    echo "\`" >> pages.js
    cat "$file" >> pages.js
    echo "\`," >> pages.js
done

echo "};" >> pages.js