// ⚠️ Do not edit this file! It is created by the pages_js_create.sh script.
const pages = {
    "home": `
<h1 style="margin-top: -7px;">all AI</h1>
<h1>no Blabla</h1>
<h1><a href="mailto:bla@nohype.ai">bla@nohype.ai</a></h1>
<br><br><br><br>
<div style="display: flex; gap: 80px; align-items: start; flex-wrap: wrap;">
    <div style="max-width: 200px; text-align: center;">
        <img src="team/manuela.jpg" alt="Manuela Hebel" style="max-width: 300px; border-radius: 50%; object-fit: cover; display: block; margin: 0 auto;">
        <p>
            Manuela Hebel<br>
            Senior Consultant<br>
            <a href="mailto:manuela@nohype.ai">manuela@nohype.ai</a><br><br>
            <span style="display: flex; gap: 20px; justify-content: center;">
                <a href="https://www.linkedin.com/in/manuelahebel" target="_blank"><img src="social-icons/linkedin.svg" alt="LinkedIn" style="width: 24px; height: 24px; vertical-align: middle; filter: invert(1) brightness(0.5);"></a>
                <a href="https://manuela-hebel.de" target="_blank"><img src="social-icons/globe2.svg" alt="Website" style="width: 24px; height: 24px; vertical-align: middle; filter: invert(1) brightness(0.5);"></a>
            </span>
        </p>
    </div>
    <div style="max-width: 200px; text-align: center;">
        <img src="team/sebastian.jpg" alt="Sebastian Fichtner" style="max-width: 300px; border-radius: 50%; object-fit: cover; display: block; margin: 0 auto;">
        <p>
            Sebastian Fichtner<br>
            CEO, Software Architect<br>
            <a href="mailto:sebastian@nohype.ai">sebastian@nohype.ai</a><br><br>
            <span style="display: flex; gap: 20px; justify-content: center;">
                <a href="team/sebastian cv.pdf" target="_blank"><img src="social-icons/file-earmark-pdf.svg" alt="CV" style="width: 24px; height: 24px; vertical-align: middle; filter: invert(1) brightness(0.5);"></a>
                <a href="https://github.com/codeface-io" target="_blank"><img src="social-icons/github.svg" alt="GitHub" style="width: 24px; height: 24px; vertical-align: middle; filter: invert(1) brightness(0.5);"></a>
                <a href="https://www.linkedin.com/in/codeface-io" target="_blank"><img src="social-icons/linkedin.svg" alt="LinkedIn" style="width: 24px; height: 24px; vertical-align: middle; filter: invert(1) brightness(0.5);"></a>
            </span>
        </p>
    </div>
</div>
    `,
    "imprint": `
<h1 style="margin-top: -7px;">Imprint</h1>
<table>
    <tbody>
        <tr>
            <td>Business Name</td>
            <td>Nohype AI GmbH</td>
        </tr>
        <tr>
            <td>UID</td>
            <td>CHE-185.499.430</td>
        </tr>
        <tr>
            <td>CH-ID</td>
            <td>CH-170-4023713-9</td>
        </tr>
        <tr>
            <td>Address</td>
            <td>Nohype AI GmbH<br>c/o Domiix.ch GmbH<br>Baarerstrasse 107<br>6300 Zug, Switzerland</td>
        </tr>
        <tr>
            <td style="padding-right: 20px;">
                Owner & Managing Director
            </td>
            <td>Sebastian Fichtner</td>
        </tr>
        <tr>
            <td>Content Editor</td>
            <td>Sebastian Fichtner</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>hi@nohype.ai</td>
        </tr>
    </tbody>
</table>
    `,
};
