#!/usr/bin/env bash

set -euo pipefail
shopt -s nullglob

{
  printf '%s\n' "// ⚠️ Do not edit this file! It is created by the pages_js_create.sh script."
  printf '%s\n' "const pages = {"

  for file in pages/*.html; do
    page_name=$(basename "$file" .html)
    content=$(<"$file")

    # Escape content for JS template literals:
    # - backslashes (keep them literal)
    # - backticks (don't terminate template literal)
    # - ${ (avoid accidental interpolation)
    escaped_content=$(printf '%s' "$content" | sed -e 's/\\/\\\\/g' -e 's/`/\\`/g' -e 's/\${/\\${/g')

    printf '%s\n' "    \"${page_name}\": \`"
    printf '%s\n' "${escaped_content}"
    printf '%s\n' "    \`,"
  done

  printf '%s\n' "};"
} > pages.js
